### ISSUE TITLE
Add environment variable for sync on start

### ISSUE THREAD

**Issue by Fmstrat** [microbug/docker-ns1-dynamic-dns#2]
Add a variable that allows the user to specify if a test should occur on start, or just execute cron.

**Comment by microbug** [comment]
Doing `docker run -v /path/to/config.yml:/config.yml:ro microbug/dynamic-dns:latest /dynamic-dns.py` (note the `/dynamic-dns.py` at the end) makes the script run once (and kills the container afterwards). Is this sufficient for you?

**Comment by Fmstrat** [comment]
It is, though I'd recommend adding that to the README. Thanks!

**Comment by microbug** [comment]
Resolved with 4b2fb17.

**Comment by Fmstrat** [comment]
@microbug May want to add "--rm" to the command line to remove the container so users don't get those pesky dead containers sitting around. And man, you are fast.

**Comment by microbug** [comment]
Thanks! Resolved with 9d2eef3.
